# 首次入科评估同步配置
first-assessment-sync.form-option-configs.ruyuanhulipinggudan.dependency-field=shzlnl
first-assessment-sync.form-option-configs.ruyuanhulipinggudan.dependency-options[NONE]=shzlnl1
first-assessment-sync.form-option-configs.ruyuanhulipinggudan.dependency-options[MILD]=shzlnl2
first-assessment-sync.form-option-configs.ruyuanhulipinggudan.dependency-options[MODERATE]=shzlnl3
first-assessment-sync.form-option-configs.ruyuanhulipinggudan.dependency-options[SEVERE]=shzlnl4
first-assessment-sync.form-option-configs.ruyuanhulipinggudan.fall-method-field=lcpdf,mpff
first-assessment-sync.form-option-configs.ruyuanhulipinggudan.fall-method-options[CLINICAL]=linchuangpandingfa
first-assessment-sync.form-option-configs.ruyuanhulipinggudan.fall-method-options[MORSE]=Morsepingfenfa

first-assessment-sync.form-option-configs.zhuanruhulipinggudan.dependency-field=shzlnl
first-assessment-sync.form-option-configs.zhuanruhulipinggudan.dependency-options[NONE]=shzlnl1
first-assessment-sync.form-option-configs.zhuanruhulipinggudan.dependency-options[MILD]=shzlnl2
first-assessment-sync.form-option-configs.zhuanruhulipinggudan.dependency-options[MODERATE]=shzlnl3
first-assessment-sync.form-option-configs.zhuanruhulipinggudan.dependency-options[SEVERE]=shzlnl4
first-assessment-sync.form-option-configs.zhuanruhulipinggudan.fall-method-field=lcpdf,mpff
first-assessment-sync.form-option-configs.zhuanruhulipinggudan.fall-method-options[CLINICAL]=linchuangpandingfa
first-assessment-sync.form-option-configs.zhuanruhulipinggudan.fall-method-options[MORSE]=Morsepingfenfa
